---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/hg3ads37/cotabemnegocios.com.br/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R enviar-lead.php $DEPLOYPATH
    - /bin/cp -R robots.txt $DEPLOYPATH
    - /bin/cp -R sitemap.xml $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
